name: PurseStringsGUI-Deploy

on:
  workflow_run:
    workflows: ["PurseStringsGUI-Build"]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
env:
   WORKINGDIR: ${{ github.workspace }}/deploy

jobs:
  deploy-from-blob:
    runs-on: ubuntu-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.PS_APP_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.PS_APP_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Create working directory
      run: mkdir -p "${{ env.WORKINGDIR }}"

    - name: Download Artifacts from Blob Storage
      run: |
        az storage blob download-batch \
          --account-name ${{ secrets.PS_STORAGE_ACCOUNT_NAME }} \
          --destination "${{ env.WORKINGDIR }}" \
          --source ${{ secrets.PS_STORAGE_BUILD_CONTAINER }}/GUI \
          --pattern '*' \
          --auth-mode login

    - name: Move files to root directory
      run: |
        mv "${{ env.WORKINGDIR }}/GUI/"* "${{ env.WORKINGDIR }}/"
        rm -rf "${{ env.WORKINGDIR }}/GUI"

    - name: Add web.config for Angular
      run: |
        echo '<configuration>
          <system.webServer>
            <rewrite>
              <rules>
                <rule name="Angular Routes" stopProcessing="true">
                  <match url=".*" />
                  <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                  </conditions>
                  <action type="Rewrite" url="/" />
                </rule>
              </rules>
            </rewrite>
            <staticContent>
              <mimeMap fileExtension=".json" mimeType="application/json" />
            </staticContent>
          </system.webServer>
        </configuration>' > "${{ env.WORKINGDIR }}/web.config"

    - name: Clean Azure App Service Directory
      run: mkdir empty-dir

    - name: Deploy empty folder to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.PS_APP_GUI_SERVICE_NAME }}
        package: empty-dir

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.PS_APP_GUI_SERVICE_NAME }}
        package: ${{ env.WORKINGDIR }}
